name = "FLOP"
version = "0.14.0"
license = "MIT"
author = "Tomoiro Degawa"
maintainer = "@degawa/flop"
copyright = "Copyright 2023, Tomohiro Degawa"

[build]
auto-executables = false
auto-tests = true
auto-examples = true

[install]
library = true

[dependencies]
VTKFortran = {git="https://github.com/degawa/VTKFortran", branch="vtkfortran-fpm"}
stdlib = { git="https://github.com/fortran-lang/stdlib", branch="stdlib-fpm" }